<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tin</string>
	</array>
	<key>name</key>
	<string>tin</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#(?i)(if|case|continue|default|while|else|elseif|endif|break|for|foreach|forall|return|switch)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#(?i)(action|alias|all|bell|buffer|chat|class|config|cr|cursor|debug|default|delay|echo|end|event|function|gag|greeting|grep|help|highlight|history|ignore|info|kill|line|list|log|loop|macro|map|math|message|parse|path|pathdir|prompt|read|regexp|replace|return|run|scan|script|send|session|showme|split|substitute|suspend|system|tab|textin|ticker|unvariable|variable|var|write|zap|unticker|undelay)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#nop</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$({\w+})|\$(\w+))</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;...&gt;</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%([\-\+\w+|\.]+)</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.tin</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tin</string>
	<key>uuid</key>
	<string>0538D725-C1EB-4EB3-A85A-1DB77A624BF8</string>
</dict>
</plist>
